# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://Ianfeather.github.com/ianfeatherV3
title: Ian Feather
subtitle: Code &amp; literature
author: Ian Feather
simple_search: http://google.com/search
description:
date_format: "ordinal"
subscribe_rss: /atom.xml
subscribe_email: info@ianfeather.co.uk
email: info@ianfeather.co.uk

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /ianfeatherV3
permalink: /:title/
source: _source
destination: _site
include: ['.htaccess']
markdown: maruku

paginate: 3          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html]

# Google Analytics
google_analytics_tracking_id: UA-18556757-8
